[2024-03-27T02:06:00.331+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-27T02:06:00.375+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-27T02:06:00.377+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-27T02:06:00.518+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-26 00:00:00+00:00
[2024-03-27T02:06:00.557+0000] {standard_task_runner.py:60} INFO - Started process 315 to run task
[2024-03-27T02:06:00.597+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpe254ssbi']
[2024-03-27T02:06:00.634+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask export_data_to_db
[2024-03-27T02:06:00.804+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T02:06:01.170+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [running]> on host 81b1c16c3e11
[2024-03-27T02:06:02.005+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-03-27T02:06:02.014+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-27T02:06:02.022+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-26 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-27T02:06:02.111+0000] {subprocess.py:86} INFO - Output:
[2024-03-27T02:06:05.407+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-27T02:06:05.548+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240326T000000, start_date=20240327T020600, end_date=20240327T020605
[2024-03-27T02:06:05.822+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-27T02:06:05.905+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-27T02:42:21.213+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-27T02:42:21.295+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-27T02:42:21.307+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-27T02:42:21.505+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-26 00:00:00+00:00
[2024-03-27T02:42:21.523+0000] {standard_task_runner.py:60} INFO - Started process 311 to run task
[2024-03-27T02:42:21.537+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmppxhbfscm']
[2024-03-27T02:42:21.558+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask export_data_to_db
[2024-03-27T02:42:21.767+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T02:42:22.147+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [running]> on host c1d14084e0e9
[2024-03-27T02:42:22.652+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-03-27T02:42:22.657+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-27T02:42:22.662+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-26 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-27T02:42:22.701+0000] {subprocess.py:86} INFO - Output:
[2024-03-27T02:42:24.391+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-27T02:42:24.552+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240326T000000, start_date=20240327T024221, end_date=20240327T024224
[2024-03-27T02:42:24.658+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-27T02:42:25.441+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-27T19:26:21.138+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-27T19:26:21.177+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-27T19:26:21.186+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-27T19:26:21.322+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-26 00:00:00+00:00
[2024-03-27T19:26:21.345+0000] {standard_task_runner.py:60} INFO - Started process 356 to run task
[2024-03-27T19:26:21.401+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmps04o56yk']
[2024-03-27T19:26:21.424+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-03-27T19:26:21.544+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T19:26:21.768+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [running]> on host a178f5bbaa10
[2024-03-27T19:26:22.228+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-03-27T19:26:22.235+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-27T19:26:22.240+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-26 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-27T19:26:22.305+0000] {subprocess.py:86} INFO - Output:
[2024-03-27T19:26:23.283+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-27T19:26:23.445+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240326T000000, start_date=20240327T192621, end_date=20240327T192623
[2024-03-27T19:26:23.850+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-27T19:26:23.905+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-29T01:37:38.644+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-29T01:37:38.690+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-29T01:37:38.697+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-29T01:37:39.051+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-26 00:00:00+00:00
[2024-03-29T01:37:39.083+0000] {standard_task_runner.py:60} INFO - Started process 358 to run task
[2024-03-29T01:37:39.097+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmplvn0gri3']
[2024-03-29T01:37:39.108+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask export_data_to_db
[2024-03-29T01:37:39.321+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-29T01:37:40.003+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [running]> on host 48a08da0e38c
[2024-03-29T01:37:40.596+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-03-29T01:37:40.609+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-29T01:37:40.614+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-26 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-29T01:37:40.690+0000] {subprocess.py:86} INFO - Output:
[2024-03-29T01:37:43.321+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-29T01:37:43.543+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240326T000000, start_date=20240329T013738, end_date=20240329T013743
[2024-03-29T01:37:43.646+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-29T01:37:43.808+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-29T02:18:17.699+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-29T02:18:17.765+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-29T02:18:17.804+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-29T02:18:17.928+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-26 00:00:00+00:00
[2024-03-29T02:18:17.945+0000] {standard_task_runner.py:60} INFO - Started process 345 to run task
[2024-03-29T02:18:17.975+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpwiz_ofrp']
[2024-03-29T02:18:17.988+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask export_data_to_db
[2024-03-29T02:18:18.148+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-29T02:18:18.576+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [running]> on host ca95eed9b9dd
[2024-03-29T02:18:19.239+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-03-29T02:18:19.249+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-29T02:18:19.254+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-26 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-29T02:18:19.286+0000] {subprocess.py:86} INFO - Output:
[2024-03-29T02:18:21.285+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-29T02:18:21.472+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240326T000000, start_date=20240329T021817, end_date=20240329T021821
[2024-03-29T02:18:21.610+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-29T02:18:21.679+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-30T01:02:38.540+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-30T01:02:38.590+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-30T01:02:38.608+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T01:02:38.708+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-26 00:00:00+00:00
[2024-03-30T01:02:38.719+0000] {standard_task_runner.py:60} INFO - Started process 361 to run task
[2024-03-30T01:02:38.740+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp9e43wmw3']
[2024-03-30T01:02:38.747+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask export_data_to_db
[2024-03-30T01:02:38.831+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-30T01:02:39.097+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [running]> on host 63c0a92b7fba
[2024-03-30T01:02:39.485+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-03-30T01:02:39.490+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-30T01:02:39.494+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-26 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-30T01:02:39.532+0000] {subprocess.py:86} INFO - Output:
[2024-03-30T01:02:41.488+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-30T01:02:41.813+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240326T000000, start_date=20240330T010238, end_date=20240330T010241
[2024-03-30T01:02:42.002+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-30T01:02:42.138+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-30T19:18:06.741+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-30T19:18:06.785+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-30T19:18:06.794+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T19:18:06.913+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-26 00:00:00+00:00
[2024-03-30T19:18:06.933+0000] {standard_task_runner.py:60} INFO - Started process 404 to run task
[2024-03-30T19:18:06.986+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpn1uo7x6n']
[2024-03-30T19:18:07.021+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask export_data_to_db
[2024-03-30T19:18:07.159+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-30T19:18:07.334+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [running]> on host 19ac4b08c681
[2024-03-30T19:18:07.742+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-03-30T19:18:07.749+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-30T19:18:07.760+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-26 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-30T19:18:07.845+0000] {subprocess.py:86} INFO - Output:
[2024-03-30T19:18:09.163+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-30T19:18:09.287+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240326T000000, start_date=20240330T191806, end_date=20240330T191809
[2024-03-30T19:18:09.390+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-30T19:18:09.457+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-31T23:53:09.628+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-31T23:53:09.668+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-03-31T23:53:09.673+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-31T23:53:09.731+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-26 00:00:00+00:00
[2024-03-31T23:53:09.747+0000] {standard_task_runner.py:60} INFO - Started process 297 to run task
[2024-03-31T23:53:09.768+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp3ec2ispa']
[2024-03-31T23:53:09.778+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask export_data_to_db
[2024-03-31T23:53:09.874+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-31T23:53:10.153+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [running]> on host eb2a2a17d989
[2024-03-31T23:53:10.759+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-03-31T23:53:10.770+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-31T23:53:10.784+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-26 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-31T23:53:10.828+0000] {subprocess.py:86} INFO - Output:
[2024-03-31T23:53:12.554+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-31T23:53:12.737+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240326T000000, start_date=20240331T235309, end_date=20240331T235312
[2024-03-31T23:53:12.852+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-31T23:53:12.916+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T22:57:02.768+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-04-01T22:57:02.806+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-04-01T22:57:02.812+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T22:57:02.897+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-26 00:00:00+00:00
[2024-04-01T22:57:02.908+0000] {standard_task_runner.py:60} INFO - Started process 404 to run task
[2024-04-01T22:57:02.934+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpc3zef4j0']
[2024-04-01T22:57:02.942+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask export_data_to_db
[2024-04-01T22:57:03.054+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T22:57:03.328+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [running]> on host eb2a2a17d989
[2024-04-01T22:57:03.784+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-04-01T22:57:03.793+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T22:57:03.798+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-26 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T22:57:03.848+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T22:57:05.429+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T22:57:05.710+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240326T000000, start_date=20240401T225702, end_date=20240401T225705
[2024-04-01T22:57:05.840+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T22:57:05.890+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T23:29:32.624+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-04-01T23:29:32.676+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-04-01T23:29:32.683+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T23:29:32.771+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-26 00:00:00+00:00
[2024-04-01T23:29:32.789+0000] {standard_task_runner.py:60} INFO - Started process 347 to run task
[2024-04-01T23:29:32.827+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp503vuzvu']
[2024-04-01T23:29:32.845+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask export_data_to_db
[2024-04-01T23:29:33.004+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T23:29:33.225+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [running]> on host d1eaa10b3e27
[2024-04-01T23:29:33.952+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-04-01T23:29:33.973+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T23:29:33.979+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-26 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T23:29:34.069+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T23:29:36.310+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T23:29:36.463+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240326T000000, start_date=20240401T232932, end_date=20240401T232936
[2024-04-01T23:29:36.636+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T23:29:36.718+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T23:39:41.896+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-04-01T23:39:42.141+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-04-01T23:39:42.153+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T23:39:42.296+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-26 00:00:00+00:00
[2024-04-01T23:39:42.337+0000] {standard_task_runner.py:60} INFO - Started process 282 to run task
[2024-04-01T23:39:42.406+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpyovj2p28']
[2024-04-01T23:39:42.420+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask export_data_to_db
[2024-04-01T23:39:42.579+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T23:39:42.812+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [running]> on host d0452b3aa12f
[2024-04-01T23:39:43.758+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-04-01T23:39:43.783+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T23:39:43.788+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-26 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T23:39:43.846+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T23:39:46.186+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T23:39:46.397+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240326T000000, start_date=20240401T233941, end_date=20240401T233946
[2024-04-01T23:39:46.613+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T23:39:46.727+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T23:53:07.809+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-04-01T23:53:07.877+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [queued]>
[2024-04-01T23:53:07.893+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T23:53:08.030+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-26 00:00:00+00:00
[2024-04-01T23:53:08.061+0000] {standard_task_runner.py:60} INFO - Started process 302 to run task
[2024-04-01T23:53:08.082+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-26T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpic1hkzhx']
[2024-04-01T23:53:08.098+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask export_data_to_db
[2024-04-01T23:53:08.259+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T23:53:08.734+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-26T00:00:00+00:00 [running]> on host 20ab91caeb49
[2024-04-01T23:53:09.452+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-26T00:00:00+00:00'
[2024-04-01T23:53:09.477+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T23:53:09.483+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-26 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T23:53:09.564+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T23:53:12.168+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T23:53:12.294+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240326T000000, start_date=20240401T235307, end_date=20240401T235312
[2024-04-01T23:53:12.382+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T23:53:12.444+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
