[2024-03-26T04:36:59.162+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-26T04:36:59.273+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-26T04:36:59.286+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-26T04:36:59.397+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-25 00:00:00+00:00
[2024-03-26T04:36:59.448+0000] {standard_task_runner.py:60} INFO - Started process 315 to run task
[2024-03-26T04:36:59.478+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-25T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpjmsv120k']
[2024-03-26T04:36:59.513+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask export_data_to_db
[2024-03-26T04:36:59.837+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-26T04:37:00.261+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [running]> on host f4350bf987d3
[2024-03-26T04:37:01.081+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T00:00:00+00:00'
[2024-03-26T04:37:01.088+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-26T04:37:01.091+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-25 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-26T04:37:01.161+0000] {subprocess.py:86} INFO - Output:
[2024-03-26T04:37:03.665+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-26T04:37:03.749+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240325T000000, start_date=20240326T043659, end_date=20240326T043703
[2024-03-26T04:37:03.845+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-26T04:37:03.991+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26T05:03:11.553+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-26T05:03:11.587+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-26T05:03:11.591+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-26T05:03:11.818+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-25 00:00:00+00:00
[2024-03-26T05:03:11.847+0000] {standard_task_runner.py:60} INFO - Started process 312 to run task
[2024-03-26T05:03:11.890+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-25T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp_03d8it8']
[2024-03-26T05:03:11.925+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask export_data_to_db
[2024-03-26T05:03:12.122+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-26T05:03:12.503+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [running]> on host 2d9dc956d0da
[2024-03-26T05:03:13.428+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T00:00:00+00:00'
[2024-03-26T05:03:13.434+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-26T05:03:13.444+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-25 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-26T05:03:13.551+0000] {subprocess.py:86} INFO - Output:
[2024-03-26T05:03:16.653+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-26T05:03:16.881+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240325T000000, start_date=20240326T050311, end_date=20240326T050316
[2024-03-26T05:03:17.132+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-26T05:03:17.207+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-27T02:06:00.159+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-27T02:06:00.313+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-27T02:06:00.316+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-27T02:06:00.453+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-25 00:00:00+00:00
[2024-03-27T02:06:00.492+0000] {standard_task_runner.py:60} INFO - Started process 314 to run task
[2024-03-27T02:06:00.537+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-25T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp_n0letxt']
[2024-03-27T02:06:00.546+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-03-27T02:06:00.707+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T02:06:01.047+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [running]> on host 81b1c16c3e11
[2024-03-27T02:06:01.815+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T00:00:00+00:00'
[2024-03-27T02:06:01.826+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-27T02:06:01.845+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-25 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-27T02:06:01.970+0000] {subprocess.py:86} INFO - Output:
[2024-03-27T02:06:05.353+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-27T02:06:05.551+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240325T000000, start_date=20240327T020600, end_date=20240327T020605
[2024-03-27T02:06:05.822+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-27T02:06:05.895+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-27T02:42:22.396+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-27T02:42:22.446+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-27T02:42:22.453+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-27T02:42:22.542+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-25 00:00:00+00:00
[2024-03-27T02:42:22.566+0000] {standard_task_runner.py:60} INFO - Started process 316 to run task
[2024-03-27T02:42:22.588+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-25T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp_8s57t4q']
[2024-03-27T02:42:22.597+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask export_data_to_db
[2024-03-27T02:42:22.717+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T02:42:22.979+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [running]> on host c1d14084e0e9
[2024-03-27T02:42:23.399+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T00:00:00+00:00'
[2024-03-27T02:42:23.406+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-27T02:42:23.410+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-25 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-27T02:42:23.442+0000] {subprocess.py:86} INFO - Output:
[2024-03-27T02:42:25.513+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-27T02:42:25.600+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240325T000000, start_date=20240327T024222, end_date=20240327T024225
[2024-03-27T02:42:25.673+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-27T02:42:25.715+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-27T19:26:21.094+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-27T19:26:21.123+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-27T19:26:21.127+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-27T19:26:21.183+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-25 00:00:00+00:00
[2024-03-27T19:26:21.221+0000] {standard_task_runner.py:60} INFO - Started process 355 to run task
[2024-03-27T19:26:21.244+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-25T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp2t7a37bi']
[2024-03-27T19:26:21.275+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask export_data_to_db
[2024-03-27T19:26:21.381+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T19:26:21.585+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [running]> on host a178f5bbaa10
[2024-03-27T19:26:22.110+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T00:00:00+00:00'
[2024-03-27T19:26:22.146+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-27T19:26:22.153+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-25 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-27T19:26:22.194+0000] {subprocess.py:86} INFO - Output:
[2024-03-27T19:26:23.241+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-27T19:26:23.368+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240325T000000, start_date=20240327T192621, end_date=20240327T192623
[2024-03-27T19:26:23.600+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-27T19:26:23.831+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-29T01:37:38.403+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-29T01:37:38.549+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-29T01:37:38.584+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-29T01:37:38.714+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-25 00:00:00+00:00
[2024-03-29T01:37:38.871+0000] {standard_task_runner.py:60} INFO - Started process 356 to run task
[2024-03-29T01:37:38.913+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-25T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmplxrbgzsm']
[2024-03-29T01:37:38.941+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-03-29T01:37:39.315+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-29T01:37:39.756+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [running]> on host 48a08da0e38c
[2024-03-29T01:37:40.491+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T00:00:00+00:00'
[2024-03-29T01:37:40.497+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-29T01:37:40.527+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-25 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-29T01:37:40.633+0000] {subprocess.py:86} INFO - Output:
[2024-03-29T01:37:43.648+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-29T01:37:43.910+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240325T000000, start_date=20240329T013738, end_date=20240329T013743
[2024-03-29T01:37:44.143+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-29T01:37:44.227+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-29T02:18:18.479+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-29T02:18:18.602+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-29T02:18:18.630+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-29T02:18:18.742+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-25 00:00:00+00:00
[2024-03-29T02:18:18.758+0000] {standard_task_runner.py:60} INFO - Started process 353 to run task
[2024-03-29T02:18:18.774+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-25T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp0c84_iff']
[2024-03-29T02:18:18.805+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask export_data_to_db
[2024-03-29T02:18:18.935+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-29T02:18:19.173+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [running]> on host ca95eed9b9dd
[2024-03-29T02:18:19.986+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T00:00:00+00:00'
[2024-03-29T02:18:19.994+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-29T02:18:20.002+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-25 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-29T02:18:20.104+0000] {subprocess.py:86} INFO - Output:
[2024-03-29T02:18:21.912+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-29T02:18:22.024+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240325T000000, start_date=20240329T021818, end_date=20240329T021822
[2024-03-29T02:18:22.120+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-29T02:18:22.151+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-30T01:02:37.780+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-30T01:02:37.837+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-30T01:02:37.842+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T01:02:38.036+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-25 00:00:00+00:00
[2024-03-30T01:02:38.054+0000] {standard_task_runner.py:60} INFO - Started process 358 to run task
[2024-03-30T01:02:38.070+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-25T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp6u7k6o_7']
[2024-03-30T01:02:38.086+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-03-30T01:02:38.187+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-30T01:02:38.464+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [running]> on host 63c0a92b7fba
[2024-03-30T01:02:38.989+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T00:00:00+00:00'
[2024-03-30T01:02:38.995+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-30T01:02:39.001+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-25 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-30T01:02:39.024+0000] {subprocess.py:86} INFO - Output:
[2024-03-30T01:02:41.241+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-30T01:02:41.475+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240325T000000, start_date=20240330T010237, end_date=20240330T010241
[2024-03-30T01:02:41.686+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-30T01:02:41.897+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-30T19:18:06.765+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-30T19:18:06.831+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-30T19:18:06.836+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T19:18:06.948+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-25 00:00:00+00:00
[2024-03-30T19:18:06.970+0000] {standard_task_runner.py:60} INFO - Started process 406 to run task
[2024-03-30T19:18:06.987+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-25T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpy9lc1fgu']
[2024-03-30T19:18:06.997+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask export_data_to_db
[2024-03-30T19:18:07.091+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-30T19:18:07.379+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [running]> on host 19ac4b08c681
[2024-03-30T19:18:07.806+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T00:00:00+00:00'
[2024-03-30T19:18:07.822+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-30T19:18:07.829+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-25 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-30T19:18:07.914+0000] {subprocess.py:86} INFO - Output:
[2024-03-30T19:18:09.528+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-30T19:18:09.642+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240325T000000, start_date=20240330T191806, end_date=20240330T191809
[2024-03-30T19:18:09.735+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-30T19:18:10.090+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-31T23:53:12.894+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-31T23:53:12.930+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [queued]>
[2024-03-31T23:53:12.937+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-31T23:53:12.984+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-25 00:00:00+00:00
[2024-03-31T23:53:12.996+0000] {standard_task_runner.py:60} INFO - Started process 314 to run task
[2024-03-31T23:53:13.012+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-25T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpyfh0mhvp']
[2024-03-31T23:53:13.021+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask export_data_to_db
[2024-03-31T23:53:13.105+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-31T23:53:13.241+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-25T00:00:00+00:00 [running]> on host eb2a2a17d989
[2024-03-31T23:53:13.658+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-25T00:00:00+00:00'
[2024-03-31T23:53:13.678+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-31T23:53:13.698+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-25 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-31T23:53:13.742+0000] {subprocess.py:86} INFO - Output:
[2024-03-31T23:53:14.530+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-31T23:53:14.602+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240325T000000, start_date=20240331T235312, end_date=20240331T235314
[2024-03-31T23:53:14.651+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-31T23:53:14.690+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
