[2024-03-29T01:37:38.903+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-03-29T01:37:39.108+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-03-29T01:37:39.116+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-29T01:37:39.491+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-27 00:00:00+00:00
[2024-03-29T01:37:39.570+0000] {standard_task_runner.py:60} INFO - Started process 361 to run task
[2024-03-29T01:37:39.591+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpc3y0qcui']
[2024-03-29T01:37:39.613+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask export_data_to_db
[2024-03-29T01:37:39.899+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-29T01:37:40.382+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [running]> on host 48a08da0e38c
[2024-03-29T01:37:41.193+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-03-29T01:37:41.210+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-29T01:37:41.228+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-27 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-29T01:37:41.318+0000] {subprocess.py:86} INFO - Output:
[2024-03-29T01:37:43.715+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-29T01:37:43.941+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240327T000000, start_date=20240329T013738, end_date=20240329T013743
[2024-03-29T01:37:44.124+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-29T01:37:44.233+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-29T02:18:17.758+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-03-29T02:18:17.857+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-03-29T02:18:17.862+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-29T02:18:17.956+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-27 00:00:00+00:00
[2024-03-29T02:18:17.981+0000] {standard_task_runner.py:60} INFO - Started process 346 to run task
[2024-03-29T02:18:18.019+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpcfe6wsmn']
[2024-03-29T02:18:18.026+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask export_data_to_db
[2024-03-29T02:18:18.121+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-29T02:18:18.394+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [running]> on host ca95eed9b9dd
[2024-03-29T02:18:19.206+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-03-29T02:18:19.212+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-29T02:18:19.216+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-27 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-29T02:18:19.239+0000] {subprocess.py:86} INFO - Output:
[2024-03-29T02:18:21.542+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-29T02:18:21.714+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240327T000000, start_date=20240329T021817, end_date=20240329T021821
[2024-03-29T02:18:21.876+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-29T02:18:21.964+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-30T01:02:38.145+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-03-30T01:02:38.173+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-03-30T01:02:38.177+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T01:02:38.269+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-27 00:00:00+00:00
[2024-03-30T01:02:38.287+0000] {standard_task_runner.py:60} INFO - Started process 359 to run task
[2024-03-30T01:02:38.302+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpawjl8yrr']
[2024-03-30T01:02:38.358+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask export_data_to_db
[2024-03-30T01:02:38.462+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-30T01:02:38.687+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [running]> on host 63c0a92b7fba
[2024-03-30T01:02:39.195+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-03-30T01:02:39.203+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-30T01:02:39.208+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-27 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-30T01:02:39.242+0000] {subprocess.py:86} INFO - Output:
[2024-03-30T01:02:41.715+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-30T01:02:41.987+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240327T000000, start_date=20240330T010238, end_date=20240330T010241
[2024-03-30T01:02:42.112+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-30T01:02:42.181+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-30T19:18:06.538+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-03-30T19:18:06.572+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-03-30T19:18:06.576+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T19:18:06.633+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-27 00:00:00+00:00
[2024-03-30T19:18:06.649+0000] {standard_task_runner.py:60} INFO - Started process 401 to run task
[2024-03-30T19:18:06.667+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpgxdnk10u']
[2024-03-30T19:18:06.675+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask export_data_to_db
[2024-03-30T19:18:06.767+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-30T19:18:06.961+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [running]> on host 19ac4b08c681
[2024-03-30T19:18:07.432+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-03-30T19:18:07.438+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-30T19:18:07.444+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-27 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-30T19:18:07.486+0000] {subprocess.py:86} INFO - Output:
[2024-03-30T19:18:08.937+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-30T19:18:09.064+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240327T000000, start_date=20240330T191806, end_date=20240330T191809
[2024-03-30T19:18:09.179+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-30T19:18:09.254+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-31T23:53:12.966+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-03-31T23:53:12.993+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-03-31T23:53:12.998+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-31T23:53:13.059+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-27 00:00:00+00:00
[2024-03-31T23:53:13.074+0000] {standard_task_runner.py:60} INFO - Started process 315 to run task
[2024-03-31T23:53:13.084+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmppucsumtd']
[2024-03-31T23:53:13.090+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask export_data_to_db
[2024-03-31T23:53:13.171+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-31T23:53:13.286+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [running]> on host eb2a2a17d989
[2024-03-31T23:53:13.661+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-03-31T23:53:13.667+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-31T23:53:13.695+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-27 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-31T23:53:13.726+0000] {subprocess.py:86} INFO - Output:
[2024-03-31T23:53:14.513+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-31T23:53:14.583+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240327T000000, start_date=20240331T235312, end_date=20240331T235314
[2024-03-31T23:53:14.644+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-31T23:53:14.682+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T22:57:02.179+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-01T22:57:02.212+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-01T22:57:02.215+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T22:57:02.339+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-27 00:00:00+00:00
[2024-04-01T22:57:02.353+0000] {standard_task_runner.py:60} INFO - Started process 400 to run task
[2024-04-01T22:57:02.366+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpyr3_sl9v']
[2024-04-01T22:57:02.376+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-04-01T22:57:02.570+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T22:57:02.848+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [running]> on host eb2a2a17d989
[2024-04-01T22:57:03.413+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-04-01T22:57:03.427+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T22:57:03.449+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-27 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T22:57:03.486+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T22:57:04.967+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T22:57:05.124+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240327T000000, start_date=20240401T225702, end_date=20240401T225705
[2024-04-01T22:57:05.252+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T22:57:05.312+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T23:29:32.342+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-01T23:29:32.436+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-01T23:29:32.441+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T23:29:32.514+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-27 00:00:00+00:00
[2024-04-01T23:29:32.544+0000] {standard_task_runner.py:60} INFO - Started process 344 to run task
[2024-04-01T23:29:32.558+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpyvkwem_q']
[2024-04-01T23:29:32.579+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask export_data_to_db
[2024-04-01T23:29:32.690+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T23:29:33.019+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [running]> on host d1eaa10b3e27
[2024-04-01T23:29:33.438+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-04-01T23:29:33.463+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T23:29:33.483+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-27 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T23:29:33.614+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T23:29:36.214+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T23:29:36.403+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240327T000000, start_date=20240401T232932, end_date=20240401T232936
[2024-04-01T23:29:36.514+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T23:29:36.611+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T23:39:41.611+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-01T23:39:41.784+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-01T23:39:41.797+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T23:39:42.035+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-27 00:00:00+00:00
[2024-04-01T23:39:42.120+0000] {standard_task_runner.py:60} INFO - Started process 281 to run task
[2024-04-01T23:39:42.185+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpktmt7qts']
[2024-04-01T23:39:42.240+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-04-01T23:39:42.445+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T23:39:42.736+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [running]> on host d0452b3aa12f
[2024-04-01T23:39:43.784+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-04-01T23:39:43.797+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T23:39:43.806+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-27 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T23:39:43.855+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T23:39:46.476+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T23:39:46.681+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240327T000000, start_date=20240401T233941, end_date=20240401T233946
[2024-04-01T23:39:46.809+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T23:39:46.862+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T23:53:07.667+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-01T23:53:07.812+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-01T23:53:07.817+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T23:53:07.926+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-27 00:00:00+00:00
[2024-04-01T23:53:07.957+0000] {standard_task_runner.py:60} INFO - Started process 300 to run task
[2024-04-01T23:53:07.997+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp57x6hw00']
[2024-04-01T23:53:08.037+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-04-01T23:53:08.208+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T23:53:08.560+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [running]> on host 20ab91caeb49
[2024-04-01T23:53:09.129+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-04-01T23:53:09.140+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T23:53:09.146+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-27 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T23:53:09.237+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T23:53:12.273+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T23:53:12.408+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240327T000000, start_date=20240401T235307, end_date=20240401T235312
[2024-04-01T23:53:12.483+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T23:53:12.584+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T21:26:45.212+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-02T21:26:45.461+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-04-02T21:26:45.492+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-02T21:26:46.073+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-27 00:00:00+00:00
[2024-04-02T21:26:46.086+0000] {standard_task_runner.py:60} INFO - Started process 327 to run task
[2024-04-02T21:26:46.131+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpn906j_z7']
[2024-04-02T21:26:46.154+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask export_data_to_db
[2024-04-02T21:26:46.488+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-02T21:26:46.869+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-27T00:00:00+00:00 [running]> on host e8080c3449d7
[2024-04-02T21:26:48.756+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-04-02T21:26:48.824+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-02T21:26:48.858+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-27 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-02T21:26:48.955+0000] {subprocess.py:86} INFO - Output:
[2024-04-02T21:26:54.417+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-02T21:26:54.601+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240327T000000, start_date=20240402T212645, end_date=20240402T212654
[2024-04-02T21:26:54.716+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-02T21:26:54.797+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
