[2024-03-24T16:30:26.570+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-24T16:30:26.654+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-24T16:30:26.658+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-24T16:30:26.979+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-23 00:00:00+00:00
[2024-03-24T16:30:26.997+0000] {standard_task_runner.py:60} INFO - Started process 404 to run task
[2024-03-24T16:30:27.039+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-23T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpysomc8sr']
[2024-03-24T16:30:27.071+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask export_data_to_db
[2024-03-24T16:30:27.223+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-24T16:30:27.585+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [running]> on host cc0f04bb20f0
[2024-03-24T16:30:28.098+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-23T00:00:00+00:00'
[2024-03-24T16:30:28.115+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-24T16:30:28.123+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-23 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-24T16:30:28.223+0000] {subprocess.py:86} INFO - Output:
[2024-03-24T16:30:30.928+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-24T16:30:31.047+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240323T000000, start_date=20240324T163026, end_date=20240324T163031
[2024-03-24T16:30:31.132+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-24T16:30:31.174+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-24T16:50:41.852+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-24T16:50:41.924+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-24T16:50:41.928+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-24T16:50:42.036+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-23 00:00:00+00:00
[2024-03-24T16:50:42.068+0000] {standard_task_runner.py:60} INFO - Started process 318 to run task
[2024-03-24T16:50:42.106+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-23T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp2dgqn60l']
[2024-03-24T16:50:42.128+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask export_data_to_db
[2024-03-24T16:50:42.307+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-24T16:50:42.782+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [running]> on host 1ef4dfe662c6
[2024-03-24T16:50:43.228+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-23T00:00:00+00:00'
[2024-03-24T16:50:43.243+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-24T16:50:43.253+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-23 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-24T16:50:43.309+0000] {subprocess.py:86} INFO - Output:
[2024-03-24T16:50:45.512+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-24T16:50:45.600+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240323T000000, start_date=20240324T165041, end_date=20240324T165045
[2024-03-24T16:50:45.763+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-24T16:50:45.857+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-24T17:29:08.096+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-24T17:29:08.378+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-24T17:29:08.381+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-24T17:29:08.933+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-23 00:00:00+00:00
[2024-03-24T17:29:09.075+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-23T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpuf14qh1e']
[2024-03-24T17:29:09.028+0000] {standard_task_runner.py:60} INFO - Started process 344 to run task
[2024-03-24T17:29:09.115+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask export_data_to_db
[2024-03-24T17:29:09.412+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-24T17:29:09.752+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [running]> on host 77fbfb9df273
[2024-03-24T17:29:10.345+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-23T00:00:00+00:00'
[2024-03-24T17:29:10.356+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-24T17:29:10.360+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-23 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-24T17:29:10.461+0000] {subprocess.py:86} INFO - Output:
[2024-03-24T17:29:12.386+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-24T17:29:12.541+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240323T000000, start_date=20240324T172908, end_date=20240324T172912
[2024-03-24T17:29:12.734+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-24T17:29:12.914+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26T04:36:59.178+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-26T04:36:59.249+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-26T04:36:59.256+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-26T04:36:59.430+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-23 00:00:00+00:00
[2024-03-26T04:36:59.509+0000] {standard_task_runner.py:60} INFO - Started process 316 to run task
[2024-03-26T04:36:59.596+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-23T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmplhix2cvh']
[2024-03-26T04:36:59.605+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask export_data_to_db
[2024-03-26T04:36:59.733+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-26T04:37:00.186+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [running]> on host f4350bf987d3
[2024-03-26T04:37:00.665+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-23T00:00:00+00:00'
[2024-03-26T04:37:00.679+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-26T04:37:00.683+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-23 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-26T04:37:00.744+0000] {subprocess.py:86} INFO - Output:
[2024-03-26T04:37:03.903+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-26T04:37:04.085+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240323T000000, start_date=20240326T043659, end_date=20240326T043704
[2024-03-26T04:37:04.236+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-26T04:37:04.308+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26T05:03:11.763+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-26T05:03:11.835+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-26T05:03:11.841+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-26T05:03:11.991+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-23 00:00:00+00:00
[2024-03-26T05:03:12.033+0000] {standard_task_runner.py:60} INFO - Started process 316 to run task
[2024-03-26T05:03:12.078+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-23T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpolz83i0e']
[2024-03-26T05:03:12.114+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask export_data_to_db
[2024-03-26T05:03:12.237+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-26T05:03:12.717+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [running]> on host 2d9dc956d0da
[2024-03-26T05:03:13.478+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-23T00:00:00+00:00'
[2024-03-26T05:03:13.482+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-26T05:03:13.484+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-23 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-26T05:03:13.558+0000] {subprocess.py:86} INFO - Output:
[2024-03-26T05:03:16.455+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-26T05:03:16.644+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240323T000000, start_date=20240326T050311, end_date=20240326T050316
[2024-03-26T05:03:16.844+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-26T05:03:16.971+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-27T02:06:00.295+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-27T02:06:00.329+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-27T02:06:00.330+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-27T02:06:00.432+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-23 00:00:00+00:00
[2024-03-27T02:06:00.467+0000] {standard_task_runner.py:60} INFO - Started process 313 to run task
[2024-03-27T02:06:00.488+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-23T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmppqkgys3x']
[2024-03-27T02:06:00.501+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask export_data_to_db
[2024-03-27T02:06:00.595+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T02:06:00.979+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [running]> on host 81b1c16c3e11
[2024-03-27T02:06:01.704+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-23T00:00:00+00:00'
[2024-03-27T02:06:01.716+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-27T02:06:01.727+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-23 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-27T02:06:01.799+0000] {subprocess.py:86} INFO - Output:
[2024-03-27T02:06:04.709+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-27T02:06:05.195+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240323T000000, start_date=20240327T020600, end_date=20240327T020605
[2024-03-27T02:06:05.432+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-27T02:06:05.607+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-27T02:42:21.358+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-27T02:42:21.394+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-27T02:42:21.401+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-27T02:42:21.581+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-23 00:00:00+00:00
[2024-03-27T02:42:21.624+0000] {standard_task_runner.py:60} INFO - Started process 313 to run task
[2024-03-27T02:42:21.652+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-23T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp_7clqln9']
[2024-03-27T02:42:21.669+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask export_data_to_db
[2024-03-27T02:42:21.826+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T02:42:22.080+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [running]> on host c1d14084e0e9
[2024-03-27T02:42:22.633+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-23T00:00:00+00:00'
[2024-03-27T02:42:22.643+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-27T02:42:22.662+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-23 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-27T02:42:22.692+0000] {subprocess.py:86} INFO - Output:
[2024-03-27T02:42:24.268+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-27T02:42:24.407+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240323T000000, start_date=20240327T024221, end_date=20240327T024224
[2024-03-27T02:42:24.521+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-27T02:42:24.608+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-27T19:26:21.153+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-27T19:26:21.209+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-27T19:26:21.213+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-27T19:26:21.348+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-23 00:00:00+00:00
[2024-03-27T19:26:21.381+0000] {standard_task_runner.py:60} INFO - Started process 357 to run task
[2024-03-27T19:26:21.381+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-23T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpa4u9bikx']
[2024-03-27T19:26:21.415+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask export_data_to_db
[2024-03-27T19:26:21.514+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T19:26:21.735+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [running]> on host a178f5bbaa10
[2024-03-27T19:26:22.290+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-23T00:00:00+00:00'
[2024-03-27T19:26:22.304+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-27T19:26:22.313+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-23 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-27T19:26:22.380+0000] {subprocess.py:86} INFO - Output:
[2024-03-27T19:26:23.344+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-27T19:26:23.546+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240323T000000, start_date=20240327T192621, end_date=20240327T192623
[2024-03-27T19:26:23.899+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-27T19:26:23.995+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-29T01:37:38.594+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-29T01:37:38.642+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-29T01:37:38.648+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-29T01:37:38.891+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-23 00:00:00+00:00
[2024-03-29T01:37:38.929+0000] {standard_task_runner.py:60} INFO - Started process 357 to run task
[2024-03-29T01:37:38.956+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-23T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp6erj6ewh']
[2024-03-29T01:37:39.062+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask export_data_to_db
[2024-03-29T01:37:39.340+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-29T01:37:40.070+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [running]> on host 48a08da0e38c
[2024-03-29T01:37:40.714+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-23T00:00:00+00:00'
[2024-03-29T01:37:40.732+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-29T01:37:40.739+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-23 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-29T01:37:40.804+0000] {subprocess.py:86} INFO - Output:
[2024-03-29T01:37:43.319+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-29T01:37:43.556+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240323T000000, start_date=20240329T013738, end_date=20240329T013743
[2024-03-29T01:37:43.750+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-29T01:37:43.873+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-29T02:18:17.709+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-29T02:18:17.738+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [queued]>
[2024-03-29T02:18:17.741+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-29T02:18:17.868+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-23 00:00:00+00:00
[2024-03-29T02:18:17.879+0000] {standard_task_runner.py:60} INFO - Started process 343 to run task
[2024-03-29T02:18:17.894+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-23T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpumh31yvx']
[2024-03-29T02:18:17.910+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-03-29T02:18:18.021+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-29T02:18:18.216+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-23T00:00:00+00:00 [running]> on host ca95eed9b9dd
[2024-03-29T02:18:18.982+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-23T00:00:00+00:00'
[2024-03-29T02:18:19.000+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-29T02:18:19.009+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-23 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-29T02:18:19.061+0000] {subprocess.py:86} INFO - Output:
[2024-03-29T02:18:21.397+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-29T02:18:21.604+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240323T000000, start_date=20240329T021817, end_date=20240329T021821
[2024-03-29T02:18:21.732+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-29T02:18:21.850+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
