[2024-03-24T16:30:26.584+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-03-24T16:30:26.684+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-03-24T16:30:26.694+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-24T16:30:26.971+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-20 00:00:00+00:00
[2024-03-24T16:30:27.031+0000] {standard_task_runner.py:60} INFO - Started process 405 to run task
[2024-03-24T16:30:27.054+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-20T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpgru33mdi']
[2024-03-24T16:30:27.073+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-03-24T16:30:27.180+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-24T16:30:27.359+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [running]> on host cc0f04bb20f0
[2024-03-24T16:30:27.739+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-20T00:00:00+00:00'
[2024-03-24T16:30:27.750+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-24T16:30:27.769+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-20 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-24T16:30:27.848+0000] {subprocess.py:86} INFO - Output:
[2024-03-24T16:30:30.290+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-24T16:30:30.535+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240320T000000, start_date=20240324T163026, end_date=20240324T163030
[2024-03-24T16:30:30.715+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-24T16:30:30.827+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-24T16:50:41.573+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-03-24T16:50:41.635+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-03-24T16:50:41.637+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-24T16:50:41.739+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-20 00:00:00+00:00
[2024-03-24T16:50:41.773+0000] {standard_task_runner.py:60} INFO - Started process 316 to run task
[2024-03-24T16:50:41.805+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-20T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpvx58slr6']
[2024-03-24T16:50:41.815+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask export_data_to_db
[2024-03-24T16:50:41.944+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-24T16:50:42.316+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [running]> on host 1ef4dfe662c6
[2024-03-24T16:50:42.869+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-20T00:00:00+00:00'
[2024-03-24T16:50:42.874+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-24T16:50:42.878+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-20 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-24T16:50:42.905+0000] {subprocess.py:86} INFO - Output:
[2024-03-24T16:50:45.050+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-24T16:50:45.185+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240320T000000, start_date=20240324T165041, end_date=20240324T165045
[2024-03-24T16:50:45.274+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-24T16:50:45.350+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-24T17:29:08.148+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-03-24T17:29:08.230+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-03-24T17:29:08.239+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-24T17:29:08.700+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-20 00:00:00+00:00
[2024-03-24T17:29:08.859+0000] {standard_task_runner.py:60} INFO - Started process 343 to run task
[2024-03-24T17:29:08.871+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-20T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpe6_8ji2b']
[2024-03-24T17:29:08.914+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask export_data_to_db
[2024-03-24T17:29:09.130+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-24T17:29:09.620+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [running]> on host 77fbfb9df273
[2024-03-24T17:29:10.130+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-20T00:00:00+00:00'
[2024-03-24T17:29:10.134+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-24T17:29:10.137+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-20 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-24T17:29:10.225+0000] {subprocess.py:86} INFO - Output:
[2024-03-24T17:29:12.350+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-24T17:29:12.489+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240320T000000, start_date=20240324T172908, end_date=20240324T172912
[2024-03-24T17:29:12.593+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-24T17:29:12.764+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26T04:36:58.661+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-03-26T04:36:58.696+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-03-26T04:36:58.698+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-26T04:36:58.772+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-20 00:00:00+00:00
[2024-03-26T04:36:58.846+0000] {standard_task_runner.py:60} INFO - Started process 313 to run task
[2024-03-26T04:36:58.927+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-20T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpecfofpwu']
[2024-03-26T04:36:58.959+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-03-26T04:36:59.110+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-26T04:36:59.620+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [running]> on host f4350bf987d3
[2024-03-26T04:37:00.528+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-20T00:00:00+00:00'
[2024-03-26T04:37:00.549+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-26T04:37:00.577+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-20 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-26T04:37:00.692+0000] {subprocess.py:86} INFO - Output:
[2024-03-26T04:37:03.524+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-26T04:37:03.693+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240320T000000, start_date=20240326T043658, end_date=20240326T043703
[2024-03-26T04:37:03.916+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-26T04:37:04.023+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26T05:03:11.722+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-03-26T05:03:11.760+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [queued]>
[2024-03-26T05:03:11.762+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-26T05:03:11.870+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-20 00:00:00+00:00
[2024-03-26T05:03:11.913+0000] {standard_task_runner.py:60} INFO - Started process 315 to run task
[2024-03-26T05:03:11.953+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-20T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp3jramf61']
[2024-03-26T05:03:12.003+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-03-26T05:03:12.189+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-26T05:03:12.868+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-20T00:00:00+00:00 [running]> on host 2d9dc956d0da
[2024-03-26T05:03:13.649+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-20T00:00:00+00:00'
[2024-03-26T05:03:13.655+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-26T05:03:13.660+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-20 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-26T05:03:13.684+0000] {subprocess.py:86} INFO - Output:
[2024-03-26T05:03:16.275+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-26T05:03:16.453+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240320T000000, start_date=20240326T050311, end_date=20240326T050316
[2024-03-26T05:03:16.898+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-26T05:03:17.071+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
