[2024-03-30T01:02:38.315+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-03-30T01:02:38.394+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-03-30T01:02:38.397+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T01:02:38.463+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-29 00:00:00+00:00
[2024-03-30T01:02:38.494+0000] {standard_task_runner.py:60} INFO - Started process 360 to run task
[2024-03-30T01:02:38.512+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-29T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp0cptfv0s']
[2024-03-30T01:02:38.525+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask export_data_to_db
[2024-03-30T01:02:38.644+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-30T01:02:38.900+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [running]> on host 63c0a92b7fba
[2024-03-30T01:02:39.421+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-29T00:00:00+00:00'
[2024-03-30T01:02:39.428+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-30T01:02:39.433+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-29 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-30T01:02:39.471+0000] {subprocess.py:86} INFO - Output:
[2024-03-30T01:02:41.789+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-30T01:02:42.081+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240329T000000, start_date=20240330T010238, end_date=20240330T010242
[2024-03-30T01:02:42.193+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-30T01:02:42.244+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-30T19:18:06.792+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-03-30T19:18:06.843+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-03-30T19:18:06.846+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T19:18:06.925+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-29 00:00:00+00:00
[2024-03-30T19:18:06.936+0000] {standard_task_runner.py:60} INFO - Started process 405 to run task
[2024-03-30T19:18:06.957+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-29T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpjg_yn64s']
[2024-03-30T19:18:06.967+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask export_data_to_db
[2024-03-30T19:18:07.047+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-30T19:18:07.235+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [running]> on host 19ac4b08c681
[2024-03-30T19:18:07.612+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-29T00:00:00+00:00'
[2024-03-30T19:18:07.638+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-30T19:18:07.643+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-29 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-30T19:18:07.672+0000] {subprocess.py:86} INFO - Output:
[2024-03-30T19:18:09.133+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-30T19:18:09.293+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240329T000000, start_date=20240330T191806, end_date=20240330T191809
[2024-03-30T19:18:09.401+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-30T19:18:09.485+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-31T23:53:09.506+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-03-31T23:53:09.544+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-03-31T23:53:09.550+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-31T23:53:09.610+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-29 00:00:00+00:00
[2024-03-31T23:53:09.623+0000] {standard_task_runner.py:60} INFO - Started process 295 to run task
[2024-03-31T23:53:09.646+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-29T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp72ro96ns']
[2024-03-31T23:53:09.657+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask export_data_to_db
[2024-03-31T23:53:09.726+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-31T23:53:09.880+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [running]> on host eb2a2a17d989
[2024-03-31T23:53:10.339+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-29T00:00:00+00:00'
[2024-03-31T23:53:10.352+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-31T23:53:10.371+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-29 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-31T23:53:10.406+0000] {subprocess.py:86} INFO - Output:
[2024-03-31T23:53:11.968+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-31T23:53:12.223+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240329T000000, start_date=20240331T235309, end_date=20240331T235312
[2024-03-31T23:53:12.432+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-31T23:53:12.530+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T22:57:01.997+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-01T22:57:02.023+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-01T22:57:02.028+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T22:57:02.113+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-29 00:00:00+00:00
[2024-04-01T22:57:02.147+0000] {standard_task_runner.py:60} INFO - Started process 399 to run task
[2024-04-01T22:57:02.161+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-29T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpp9787hal']
[2024-04-01T22:57:02.171+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask export_data_to_db
[2024-04-01T22:57:02.256+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T22:57:02.430+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [running]> on host eb2a2a17d989
[2024-04-01T22:57:02.940+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-29T00:00:00+00:00'
[2024-04-01T22:57:02.947+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T22:57:02.953+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-29 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T22:57:03.006+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T22:57:04.563+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T22:57:04.695+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240329T000000, start_date=20240401T225702, end_date=20240401T225704
[2024-04-01T22:57:04.784+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T22:57:05.009+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T23:29:32.326+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-01T23:29:32.414+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-01T23:29:32.422+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T23:29:32.529+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-29 00:00:00+00:00
[2024-04-01T23:29:32.541+0000] {standard_task_runner.py:60} INFO - Started process 343 to run task
[2024-04-01T23:29:32.582+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-29T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpv5i73kj7']
[2024-04-01T23:29:32.594+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-04-01T23:29:32.701+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T23:29:33.094+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [running]> on host d1eaa10b3e27
[2024-04-01T23:29:33.735+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-29T00:00:00+00:00'
[2024-04-01T23:29:33.744+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T23:29:33.755+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-29 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T23:29:33.859+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T23:29:36.713+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T23:29:36.843+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240329T000000, start_date=20240401T232932, end_date=20240401T232936
[2024-04-01T23:29:36.983+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T23:29:37.225+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T23:39:41.516+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-01T23:39:41.653+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-01T23:39:41.662+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T23:39:41.966+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-29 00:00:00+00:00
[2024-04-01T23:39:42.100+0000] {standard_task_runner.py:60} INFO - Started process 280 to run task
[2024-04-01T23:39:42.171+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-29T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmphlahxaq9']
[2024-04-01T23:39:42.195+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask export_data_to_db
[2024-04-01T23:39:42.345+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T23:39:42.656+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [running]> on host d0452b3aa12f
[2024-04-01T23:39:43.571+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-29T00:00:00+00:00'
[2024-04-01T23:39:43.585+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T23:39:43.590+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-29 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T23:39:43.634+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T23:39:46.036+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T23:39:46.195+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240329T000000, start_date=20240401T233941, end_date=20240401T233946
[2024-04-01T23:39:46.381+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T23:39:46.539+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T23:53:07.171+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-01T23:53:07.407+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-01T23:53:07.426+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T23:53:07.638+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-29 00:00:00+00:00
[2024-04-01T23:53:07.666+0000] {standard_task_runner.py:60} INFO - Started process 297 to run task
[2024-04-01T23:53:07.761+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-29T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpp4a709f2']
[2024-04-01T23:53:07.801+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask export_data_to_db
[2024-04-01T23:53:08.005+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T23:53:08.413+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [running]> on host 20ab91caeb49
[2024-04-01T23:53:09.248+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-29T00:00:00+00:00'
[2024-04-01T23:53:09.287+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T23:53:09.298+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-29 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T23:53:09.356+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T23:53:11.472+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T23:53:11.676+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240329T000000, start_date=20240401T235307, end_date=20240401T235311
[2024-04-01T23:53:11.785+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T23:53:11.877+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T21:26:45.137+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-02T21:26:45.402+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [queued]>
[2024-04-02T21:26:45.448+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-02T21:26:46.039+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-29 00:00:00+00:00
[2024-04-02T21:26:46.113+0000] {standard_task_runner.py:60} INFO - Started process 328 to run task
[2024-04-02T21:26:46.163+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-29T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp109sq5xm']
[2024-04-02T21:26:46.218+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-04-02T21:26:46.474+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-02T21:26:47.021+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-29T00:00:00+00:00 [running]> on host e8080c3449d7
[2024-04-02T21:26:48.804+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-29T00:00:00+00:00'
[2024-04-02T21:26:48.836+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-02T21:26:48.863+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-29 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-02T21:26:48.948+0000] {subprocess.py:86} INFO - Output:
[2024-04-02T21:26:54.622+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-02T21:26:54.792+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240329T000000, start_date=20240402T212645, end_date=20240402T212654
[2024-04-02T21:26:54.921+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-02T21:26:55.091+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
