[2024-03-24T16:30:08.656+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.import_tomtom_data_to_csv scheduled__2024-03-18T00:00:00+00:00 [queued]>
[2024-03-24T16:30:08.687+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.import_tomtom_data_to_csv scheduled__2024-03-18T00:00:00+00:00 [queued]>
[2024-03-24T16:30:08.689+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-24T16:30:08.757+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): import_tomtom_data_to_csv> on 2024-03-18 00:00:00+00:00
[2024-03-24T16:30:08.820+0000] {standard_task_runner.py:60} INFO - Started process 363 to run task
[2024-03-24T16:30:08.925+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'import_tomtom_data_to_csv', 'scheduled__2024-03-18T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpzid23x7z']
[2024-03-24T16:30:08.960+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask import_tomtom_data_to_csv
[2024-03-24T16:30:09.140+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-24T16:30:09.622+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.import_tomtom_data_to_csv scheduled__2024-03-18T00:00:00+00:00 [running]> on host cc0f04bb20f0
[2024-03-24T16:30:10.513+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='import_tomtom_data_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-18T00:00:00+00:00'
[2024-03-24T16:30:10.518+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-24T16:30:10.525+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_ingestion.py --date 2024-03-18']
[2024-03-24T16:30:10.632+0000] {subprocess.py:86} INFO - Output:
[2024-03-24T16:30:23.601+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-24T16:30:23.794+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=import_tomtom_data_to_csv, execution_date=20240318T000000, start_date=20240324T163008, end_date=20240324T163023
[2024-03-24T16:30:23.960+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-24T16:30:24.045+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-24T16:50:24.037+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.import_tomtom_data_to_csv scheduled__2024-03-18T00:00:00+00:00 [queued]>
[2024-03-24T16:50:24.084+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.import_tomtom_data_to_csv scheduled__2024-03-18T00:00:00+00:00 [queued]>
[2024-03-24T16:50:24.088+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-24T16:50:24.242+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): import_tomtom_data_to_csv> on 2024-03-18 00:00:00+00:00
[2024-03-24T16:50:24.303+0000] {standard_task_runner.py:60} INFO - Started process 261 to run task
[2024-03-24T16:50:24.334+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'import_tomtom_data_to_csv', 'scheduled__2024-03-18T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp1cnr34vs']
[2024-03-24T16:50:24.360+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask import_tomtom_data_to_csv
[2024-03-24T16:50:24.498+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-24T16:50:25.194+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.import_tomtom_data_to_csv scheduled__2024-03-18T00:00:00+00:00 [running]> on host 1ef4dfe662c6
[2024-03-24T16:50:26.013+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='import_tomtom_data_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-18T00:00:00+00:00'
[2024-03-24T16:50:26.033+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-24T16:50:26.063+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_ingestion.py --date 2024-03-18']
[2024-03-24T16:50:26.223+0000] {subprocess.py:86} INFO - Output:
[2024-03-24T16:50:38.717+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-24T16:50:38.836+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=import_tomtom_data_to_csv, execution_date=20240318T000000, start_date=20240324T165024, end_date=20240324T165038
[2024-03-24T16:50:38.936+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-24T16:50:39.070+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-24T17:28:52.526+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.import_tomtom_data_to_csv scheduled__2024-03-18T00:00:00+00:00 [queued]>
[2024-03-24T17:28:52.614+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.import_tomtom_data_to_csv scheduled__2024-03-18T00:00:00+00:00 [queued]>
[2024-03-24T17:28:52.616+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-24T17:28:52.668+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): import_tomtom_data_to_csv> on 2024-03-18 00:00:00+00:00
[2024-03-24T17:28:52.680+0000] {standard_task_runner.py:60} INFO - Started process 290 to run task
[2024-03-24T17:28:52.715+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'import_tomtom_data_to_csv', 'scheduled__2024-03-18T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpo4chj68y']
[2024-03-24T17:28:52.731+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask import_tomtom_data_to_csv
[2024-03-24T17:28:52.839+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-24T17:28:53.131+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.import_tomtom_data_to_csv scheduled__2024-03-18T00:00:00+00:00 [running]> on host 77fbfb9df273
[2024-03-24T17:28:53.849+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='import_tomtom_data_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-18T00:00:00+00:00'
[2024-03-24T17:28:53.857+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-24T17:28:53.863+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_ingestion.py --date 2024-03-18']
[2024-03-24T17:28:53.919+0000] {subprocess.py:86} INFO - Output:
[2024-03-24T17:29:04.877+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-24T17:29:04.981+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=import_tomtom_data_to_csv, execution_date=20240318T000000, start_date=20240324T172852, end_date=20240324T172904
[2024-03-24T17:29:05.085+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-24T17:29:05.202+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
