[2024-03-31T23:53:09.610+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-03-31T23:53:09.651+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-03-31T23:53:09.654+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-31T23:53:09.734+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-30 00:00:00+00:00
[2024-03-31T23:53:09.747+0000] {standard_task_runner.py:60} INFO - Started process 298 to run task
[2024-03-31T23:53:09.764+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpj5b42qt_']
[2024-03-31T23:53:09.774+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask export_data_to_db
[2024-03-31T23:53:09.845+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-31T23:53:10.098+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [running]> on host eb2a2a17d989
[2024-03-31T23:53:10.577+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-30T00:00:00+00:00'
[2024-03-31T23:53:10.597+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-31T23:53:10.626+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-30 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-31T23:53:10.718+0000] {subprocess.py:86} INFO - Output:
[2024-03-31T23:53:12.419+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-31T23:53:12.597+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240330T000000, start_date=20240331T235309, end_date=20240331T235312
[2024-03-31T23:53:12.720+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-31T23:53:12.789+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T22:57:02.639+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-01T22:57:02.675+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-01T22:57:02.680+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T22:57:02.740+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-30 00:00:00+00:00
[2024-04-01T22:57:02.761+0000] {standard_task_runner.py:60} INFO - Started process 403 to run task
[2024-04-01T22:57:02.787+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp40yu5fhn']
[2024-04-01T22:57:02.801+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask export_data_to_db
[2024-04-01T22:57:02.910+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T22:57:03.108+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [running]> on host eb2a2a17d989
[2024-04-01T22:57:03.735+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-30T00:00:00+00:00'
[2024-04-01T22:57:03.741+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T22:57:03.745+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-30 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T22:57:03.806+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T22:57:05.626+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T22:57:05.815+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240330T000000, start_date=20240401T225702, end_date=20240401T225705
[2024-04-01T22:57:05.896+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T22:57:05.933+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T23:29:32.452+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-01T23:29:32.511+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-01T23:29:32.516+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T23:29:32.641+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-30 00:00:00+00:00
[2024-04-01T23:29:32.656+0000] {standard_task_runner.py:60} INFO - Started process 346 to run task
[2024-04-01T23:29:32.690+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpynyyhazm']
[2024-04-01T23:29:32.719+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask export_data_to_db
[2024-04-01T23:29:32.826+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T23:29:33.100+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [running]> on host d1eaa10b3e27
[2024-04-01T23:29:33.938+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-30T00:00:00+00:00'
[2024-04-01T23:29:33.944+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T23:29:33.961+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-30 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T23:29:34.054+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T23:29:36.738+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T23:29:36.908+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240330T000000, start_date=20240401T232932, end_date=20240401T232936
[2024-04-01T23:29:36.994+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T23:29:37.087+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T23:39:44.570+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-01T23:39:44.605+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-01T23:39:44.616+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T23:39:44.724+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-30 00:00:00+00:00
[2024-04-01T23:39:44.767+0000] {standard_task_runner.py:60} INFO - Started process 300 to run task
[2024-04-01T23:39:44.789+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpgm4v4j6u']
[2024-04-01T23:39:44.798+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask export_data_to_db
[2024-04-01T23:39:44.920+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T23:39:45.225+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [running]> on host d0452b3aa12f
[2024-04-01T23:39:45.891+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-30T00:00:00+00:00'
[2024-04-01T23:39:45.898+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T23:39:45.903+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-30 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T23:39:45.989+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T23:39:47.257+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T23:39:47.332+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240330T000000, start_date=20240401T233944, end_date=20240401T233947
[2024-04-01T23:39:47.417+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T23:39:47.461+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-01T23:53:07.630+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-01T23:53:07.727+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-01T23:53:07.733+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T23:53:07.849+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-30 00:00:00+00:00
[2024-04-01T23:53:07.871+0000] {standard_task_runner.py:60} INFO - Started process 299 to run task
[2024-04-01T23:53:07.893+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpgkjwuqy9']
[2024-04-01T23:53:07.954+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask export_data_to_db
[2024-04-01T23:53:08.176+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-01T23:53:08.463+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [running]> on host 20ab91caeb49
[2024-04-01T23:53:09.183+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-30T00:00:00+00:00'
[2024-04-01T23:53:09.197+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-01T23:53:09.205+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-30 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-01T23:53:09.299+0000] {subprocess.py:86} INFO - Output:
[2024-04-01T23:53:11.655+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-01T23:53:11.815+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240330T000000, start_date=20240401T235307, end_date=20240401T235311
[2024-04-01T23:53:11.983+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-01T23:53:12.077+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-02T21:26:47.236+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02T21:26:47.624+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-04-02T21:26:47.632+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-02T21:26:47.971+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-30 00:00:00+00:00
[2024-04-02T21:26:48.047+0000] {standard_task_runner.py:60} INFO - Started process 330 to run task
[2024-04-02T21:26:48.103+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmps_bsh3wt']
[2024-04-02T21:26:48.148+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask export_data_to_db
[2024-04-02T21:26:48.521+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-02T21:26:49.037+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-30T00:00:00+00:00 [running]> on host e8080c3449d7
[2024-04-02T21:26:52.402+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-30T00:00:00+00:00'
[2024-04-02T21:26:52.513+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-02T21:26:52.562+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-30 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-02T21:26:53.053+0000] {subprocess.py:86} INFO - Output:
[2024-04-02T21:26:56.278+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-02T21:26:56.621+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240330T000000, start_date=20240402T212647, end_date=20240402T212656
[2024-04-02T21:26:56.950+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-02T21:26:57.331+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
