[2024-03-26T04:36:59.325+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-26T04:36:59.452+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-26T04:36:59.463+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-26T04:36:59.588+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-24 00:00:00+00:00
[2024-03-26T04:36:59.675+0000] {standard_task_runner.py:60} INFO - Started process 320 to run task
[2024-03-26T04:36:59.771+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-24T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpnyoqgupt']
[2024-03-26T04:36:59.818+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask export_data_to_db
[2024-03-26T04:37:00.092+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-26T04:37:00.514+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [running]> on host f4350bf987d3
[2024-03-26T04:37:01.187+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-24T00:00:00+00:00'
[2024-03-26T04:37:01.192+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-26T04:37:01.194+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-24 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-26T04:37:01.247+0000] {subprocess.py:86} INFO - Output:
[2024-03-26T04:37:03.805+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-26T04:37:03.927+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240324T000000, start_date=20240326T043659, end_date=20240326T043703
[2024-03-26T04:37:04.098+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-26T04:37:04.175+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26T05:03:11.561+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-26T05:03:11.602+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-26T05:03:11.604+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-26T05:03:11.824+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-24 00:00:00+00:00
[2024-03-26T05:03:11.893+0000] {standard_task_runner.py:60} INFO - Started process 314 to run task
[2024-03-26T05:03:11.922+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-24T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp3yv7xnl0']
[2024-03-26T05:03:11.942+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask export_data_to_db
[2024-03-26T05:03:12.118+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-26T05:03:12.713+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [running]> on host 2d9dc956d0da
[2024-03-26T05:03:13.499+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-24T00:00:00+00:00'
[2024-03-26T05:03:13.502+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-26T05:03:13.505+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-24 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-26T05:03:13.577+0000] {subprocess.py:86} INFO - Output:
[2024-03-26T05:03:16.592+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-26T05:03:16.698+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240324T000000, start_date=20240326T050311, end_date=20240326T050316
[2024-03-26T05:03:16.887+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-26T05:03:17.076+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-27T02:06:00.760+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-27T02:06:00.851+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-27T02:06:00.854+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-27T02:06:00.964+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-24 00:00:00+00:00
[2024-03-27T02:06:00.991+0000] {standard_task_runner.py:60} INFO - Started process 317 to run task
[2024-03-27T02:06:01.021+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-24T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpbhjti7k3']
[2024-03-27T02:06:01.035+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask export_data_to_db
[2024-03-27T02:06:01.095+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T02:06:01.229+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [running]> on host 81b1c16c3e11
[2024-03-27T02:06:01.677+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-24T00:00:00+00:00'
[2024-03-27T02:06:01.681+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-27T02:06:01.684+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-24 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-27T02:06:01.731+0000] {subprocess.py:86} INFO - Output:
[2024-03-27T02:06:05.305+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-27T02:06:05.527+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240324T000000, start_date=20240327T020600, end_date=20240327T020605
[2024-03-27T02:06:05.725+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-27T02:06:05.846+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-27T02:42:21.207+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-27T02:42:21.246+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-27T02:42:21.251+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-27T02:42:21.312+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-24 00:00:00+00:00
[2024-03-27T02:42:21.322+0000] {standard_task_runner.py:60} INFO - Started process 310 to run task
[2024-03-27T02:42:21.337+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-24T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpbadu3jmm']
[2024-03-27T02:42:21.346+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-03-27T02:42:21.474+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T02:42:21.817+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [running]> on host c1d14084e0e9
[2024-03-27T02:42:22.471+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-24T00:00:00+00:00'
[2024-03-27T02:42:22.487+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-27T02:42:22.494+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-24 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-27T02:42:22.539+0000] {subprocess.py:86} INFO - Output:
[2024-03-27T02:42:24.013+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-27T02:42:24.210+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240324T000000, start_date=20240327T024221, end_date=20240327T024224
[2024-03-27T02:42:24.315+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-27T02:42:24.394+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-27T19:26:24.507+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-27T19:26:24.554+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-27T19:26:24.558+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-27T19:26:24.619+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-24 00:00:00+00:00
[2024-03-27T19:26:24.637+0000] {standard_task_runner.py:60} INFO - Started process 369 to run task
[2024-03-27T19:26:24.647+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-24T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpfq73w_9t']
[2024-03-27T19:26:24.654+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask export_data_to_db
[2024-03-27T19:26:24.735+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-27T19:26:24.901+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [running]> on host a178f5bbaa10
[2024-03-27T19:26:25.346+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-24T00:00:00+00:00'
[2024-03-27T19:26:25.354+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-27T19:26:25.359+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-24 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-27T19:26:25.403+0000] {subprocess.py:86} INFO - Output:
[2024-03-27T19:26:26.571+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-27T19:26:26.779+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240324T000000, start_date=20240327T192624, end_date=20240327T192626
[2024-03-27T19:26:26.902+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-27T19:26:26.975+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-29T01:37:38.848+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-29T01:37:38.942+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-29T01:37:38.949+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-29T01:37:39.253+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-24 00:00:00+00:00
[2024-03-29T01:37:39.331+0000] {standard_task_runner.py:60} INFO - Started process 359 to run task
[2024-03-29T01:37:39.399+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-24T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpu2ek108z']
[2024-03-29T01:37:39.496+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask export_data_to_db
[2024-03-29T01:37:39.700+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-29T01:37:40.181+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [running]> on host 48a08da0e38c
[2024-03-29T01:37:40.754+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-24T00:00:00+00:00'
[2024-03-29T01:37:40.778+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-29T01:37:40.784+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-24 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-29T01:37:40.851+0000] {subprocess.py:86} INFO - Output:
[2024-03-29T01:37:43.884+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-29T01:37:44.139+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240324T000000, start_date=20240329T013738, end_date=20240329T013744
[2024-03-29T01:37:44.260+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-29T01:37:44.346+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-29T02:18:17.945+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-29T02:18:17.994+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-29T02:18:18.005+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-29T02:18:18.196+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-24 00:00:00+00:00
[2024-03-29T02:18:18.230+0000] {standard_task_runner.py:60} INFO - Started process 347 to run task
[2024-03-29T02:18:18.248+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-24T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpwvi8q3wj']
[2024-03-29T02:18:18.256+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask export_data_to_db
[2024-03-29T02:18:18.398+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-29T02:18:18.791+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [running]> on host ca95eed9b9dd
[2024-03-29T02:18:19.302+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-24T00:00:00+00:00'
[2024-03-29T02:18:19.309+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-29T02:18:19.313+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-24 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-29T02:18:19.368+0000] {subprocess.py:86} INFO - Output:
[2024-03-29T02:18:21.536+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-29T02:18:21.661+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240324T000000, start_date=20240329T021817, end_date=20240329T021821
[2024-03-29T02:18:21.814+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-29T02:18:21.905+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-30T01:02:37.667+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-30T01:02:37.780+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-30T01:02:37.790+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T01:02:37.889+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-24 00:00:00+00:00
[2024-03-30T01:02:37.923+0000] {standard_task_runner.py:60} INFO - Started process 356 to run task
[2024-03-30T01:02:37.940+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-24T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp7rnnewut']
[2024-03-30T01:02:37.955+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask export_data_to_db
[2024-03-30T01:02:38.093+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-30T01:02:38.378+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [running]> on host 63c0a92b7fba
[2024-03-30T01:02:38.867+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-24T00:00:00+00:00'
[2024-03-30T01:02:38.879+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-30T01:02:38.892+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-24 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-30T01:02:38.937+0000] {subprocess.py:86} INFO - Output:
[2024-03-30T01:02:40.968+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-30T01:02:41.460+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240324T000000, start_date=20240330T010237, end_date=20240330T010241
[2024-03-30T01:02:41.652+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-30T01:02:41.854+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-30T19:18:06.722+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-30T19:18:06.766+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-03-30T19:18:06.770+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T19:18:06.871+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-03-24 00:00:00+00:00
[2024-03-30T19:18:06.885+0000] {standard_task_runner.py:60} INFO - Started process 402 to run task
[2024-03-30T19:18:06.923+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-03-24T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmp3xd1yua4']
[2024-03-30T19:18:06.972+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask export_data_to_db
[2024-03-30T19:18:07.079+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-30T19:18:07.356+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-03-24T00:00:00+00:00 [running]> on host 19ac4b08c681
[2024-03-30T19:18:07.858+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-24T00:00:00+00:00'
[2024-03-30T19:18:07.863+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-30T19:18:07.867+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-03-24 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-03-30T19:18:07.905+0000] {subprocess.py:86} INFO - Output:
[2024-03-30T19:18:09.492+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-30T19:18:09.632+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240324T000000, start_date=20240330T191806, end_date=20240330T191809
[2024-03-30T19:18:09.736+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-30T19:18:10.092+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
