[2024-04-02T21:26:45.440+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-04-02T21:26:45.569+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tomtom.export_data_to_db scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-04-02T21:26:45.576+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-02T21:26:45.983+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): export_data_to_db> on 2024-04-01 00:00:00+00:00
[2024-04-02T21:26:46.017+0000] {standard_task_runner.py:60} INFO - Started process 326 to run task
[2024-04-02T21:26:46.096+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tomtom', 'export_data_to_db', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tomtom_dag.py', '--cfg-path', '/tmp/tmpc6tpw1yo']
[2024-04-02T21:26:46.133+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask export_data_to_db
[2024-04-02T21:26:46.320+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-02T21:26:46.794+0000] {task_command.py:423} INFO - Running <TaskInstance: tomtom.export_data_to_db scheduled__2024-04-01T00:00:00+00:00 [running]> on host e8080c3449d7
[2024-04-02T21:26:48.170+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tomtom' AIRFLOW_CTX_TASK_ID='export_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2024-04-02T21:26:48.232+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-02T21:26:48.238+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/tomtom_to_db.py --date 2024-04-01 --connection postgresql+psycopg2://***:***@postgres/***']
[2024-04-02T21:26:48.409+0000] {subprocess.py:86} INFO - Output:
[2024-04-02T21:26:54.499+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-02T21:26:54.657+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=tomtom, task_id=export_data_to_db, execution_date=20240401T000000, start_date=20240402T212645, end_date=20240402T212654
[2024-04-02T21:26:54.786+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-02T21:26:54.848+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
